version: '3.8'

services:
  db:
    image: postgres:15
    container_name: go-app-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:                       # ← Go アプリ用サービス
    build:
      context: ./backend     # ← Dockerfile のあるディレクトリ
      dockerfile: Dockerfile
    container_name: go-app-api
    restart: always
    ports:
      - '${APP_PORT}:8081'   # ← ホスト⇔コンテナ間のポートマッピング
    environment:
      # DB 接続情報をそのまま渡す
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URL: ${OAUTH_REDIRECT_URL}
      # もしアプリ側で別のポートを参照する場合は
      # APP_PORT: '8081'
    depends_on:
      - db

volumes:
  db_data:
